version: '3.8'

services:
  flask-app:
    build: .
    image: backend-flask:latest 
    container_name: backend-flask-app
    ports:
      - "8003:8003"
    volumes:
      - ./service-account-key.json:/app/service-account-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    env_file:
      - .env
    command: ["python3", "app.py"]
    restart: unless-stopped